### PR TITLE
version bump

### PR DESCRIPTION
**Pull request by rowbawts**

### CODE REVIEW

**Comment by DayberAlfonso** [comment]
cock

**Comment by DayberAlfonso** [comment]
👍

**Comment by rowbawts** [comment]
:+1:

**Comment by chriscamarillo** [comment]
caca

**Comment by chriscamarillo** [comment]
+1

**Comment by chriscamarillo** [comment]
:+1:

**Comment by chriscamarillo** [comment]
👍

**Comment by rowbawts** [comment]
👍

**Pull request merged**
