### PR TITLE
version bump

### PR DESCRIPTION
**Pull request by rowbawts**

### CODE REVIEW

**Comment by rowbawts** [comment]
:+1:

**Comment by chriscamarillo** [comment]
this

**Comment by chriscamarillo** [comment]
is a uselesss comment

**Comment by chriscamarillo** [comment]
+1

**Comment by chriscamarillo** [comment]
-msfgji sdfjgsjdkfg+ 1

**Comment by chriscamarillo** [comment]
+1+1~_+

**Pull request merged**
